# Generated by Django 4.2.26 on 2025-11-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityweather',
            name='wind',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
